### ISSUE TITLE
Crash minifying a Meteor application

### ISSUE THREAD

**Issue by tophsic** [yeliex/node.os#2]
I wanted to use node.os in a Meteor application (1.3.4.4). I can use it with a `meteor run` command but minifying code is crashing during `meteor build` command:

``` bash
Errors prevented bundling:                    
While minifying app code:                     
/home/christophe/.meteor/packages/standard-minifier-js/.1.0.8.96kvr1++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:196:18: Unexpected
token: name (OS)
at new JS_Parse_Error
(/home/christophe/.meteor/packages/standard-minifier-js/.1.0.8.96kvr1++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:196:18)
at js_error
(/home/christophe/.meteor/packages/standard-minifier-js/.1.0.8.96kvr1++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:204:11)
at croak (/home/christophe/.meteor/packages/standard-minifier-js/.1.0.8.96kvr1++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:675:9)
at token_error
(/home/christophe/.meteor/packages/standard-minifier-js/.1.0.8.96kvr1++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:683:9)
at unexpected
(/home/christophe/.meteor/packages/standard-minifier-js/.1.0.8.96kvr1++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:689:9)
at semicolon
(/home/christophe/.meteor/packages/standard-minifier-js/.1.0.8.96kvr1++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:709:43)
at simple_statement
(/home/christophe/.meteor/packages/standard-minifier-js/.1.0.8.96kvr1++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:889:73)
at /home/christophe/.meteor/packages/standard-minifier-js/.1.0.8.96kvr1++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:762:19
at /home/christophe/.meteor/packages/standard-minifier-js/.1.0.8.96kvr1++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:722:24
at block_ (/home/christophe/.meteor/packages/standard-minifier-js/.1.0.8.96kvr1++os+web.browser+web.cordova/plugin.minifyStdJS.os/npm/node_modules/meteor/minifier-js/node_modules/uglify-js/lib/parse.js:1002:20)
```

**Comment by yeliex** [comment]
https://github.com/yeliex/node.os/commit/7d18a3af33792872028b3a939e21d94263dfa97e
